# Generated by Django 5.2.2 on 2025-06-07 12:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
