# Generated by Django 5.2.2 on 2025-06-07 23:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_incident_geo_location_alter_incident_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='zim_adm2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm2_en', models.CharField(max_length=254)),
                ('adm2_pcode', models.CharField(max_length=254)),
                ('adm1_en', models.CharField(max_length=254)),
                ('adm1_pcode', models.CharField(max_length=254)),
                ('adm0_en', models.CharField(max_length=254)),
                ('adm0_pcode', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
